export default [
    { label: 'Affenpinscher' },
    { label: 'Afghan Hound' },
    { label: 'Airedale Terrier' },
    { label: 'Akita' },
    { label: 'Alaskan Malamute' },
    { label: 'American Bulldog' },
    { label: 'American English Coonhound' },
    { label: 'American Eskimo Dog' },
    { label: 'American Foxhound' },
    { label: 'American Hairless Terrier' },
    { label: 'American Leopard Hound' },
    { label: 'American Staffordshire Terrier' },
    { label: 'American Water Spaniel' },
    { label: 'Anatolian Shepherd Dog' },
    { label: 'Appenzeller Sennenhund' },
    { label: 'Australian Cattle Dog' },
    { label: 'Australian Kelpie' },
    { label: 'Australian Shepherd' },
    { label: 'Australian Stumpy Tail Cattle Dog' },
    { label: 'Australian Terrier' },
    { label: 'Azawakh' },
    { label: 'Barbet' },
    { label: 'Basenji' },
    { label: 'Basset Fauve de Bretagne' },
    { label: 'Basset Hound' },
    { label: 'Bavarian Mountain Scent Hound' },
    { label: 'Beagle' },
    { label: 'Bearded Collie' },
    { label: 'Beauceron' },
    { label: 'Bedlington Terrier' },
    { label: 'Belgian Laekenois' },
    { label: 'Belgian Malinois' },
    { label: 'Belgian Sheepdog' },
    { label: 'Belgian Tervuren' },
    { label: 'Bergamasco Sheepdog' },
    { label: 'Berger Picard' },
    { label: 'Bernese Mountain Dog' },
    { label: 'Bichon Frise' },
    { label: 'Biewer Terrier' },
    { label: 'Black and Tan Coonhound' },
    { label: 'Black Russian Terrier' },
    { label: 'Bloodhound' },
    { label: 'Bluetick Coonhound' },
    { label: 'Boerboel' },
    { label: 'Bohemian Shepherd' },
    { label: 'Bolognese' },
    { label: 'Border Collie' },
    { label: 'Border Terrier' },
    { label: 'Borzoi' },
    { label: 'Boston Terrier' },
    { label: 'Bouvier des Flandres' },
    { label: 'Boxer' },
    { label: 'Boykin Spaniel' },
    { label: 'Bracco Italiano' },
    { label: 'Braque du Bourbonnais' },
    { label: 'Braque Francais Pyrenean' },
    { label: 'Briard' },
    { label: 'Brittany' },
    { label: 'Broholmer' },
    { label: 'Brussels Griffon' },
    { label: 'Bull Terrier' },
    { label: 'Bulldog' },
    { label: 'Bullmastiff' },
    { label: 'Cairn Terrier' },
    { label: 'Canaan Dog' },
    { label: 'Cane Corso' },
    { label: 'Cardigan Welsh Corgi' },
    { label: 'Carolina Dog' },
    { label: 'Catahoula Leopard Dog' },
    { label: 'Caucasian Shepherd Dog' },
    { label: 'Cavalier King Charles Spaniel' },
    { label: 'Central Asian Shepherd Dog' },
    { label: 'Cesky Terrier' },
    { label: 'Chesapeake Bay Retriever' },
    { label: 'Chihuahua' },
    { label: 'Chinese Crested' },
    { label: 'Chinese Shar-Pei' },
    { label: 'Chinook' },
    { label: 'Chow Chow' },
    { label: 'Cirneco dellEtna' },
    { label: 'Clumber Spaniel' },
    { label: 'Cocker Spaniel' },
    { label: 'Collie' },
    { label: 'Coton de Tulear' },
    { label: 'Croatian Sheepdog' },
    { label: 'Curly-Coated Retriever' },
    { label: 'Czechoslovakian Vlcak' },
    { label: 'Dachshund' },
    { label: 'Dalmatian' },
    { label: 'Dandie Dinmont Terrier' },
    { label: 'Danish-Swedish Farmdog' },
    { label: 'Deutscher Wachtelhund' },
    { label: 'Doberman Pinscher' },
    { label: 'Dogo Argentino' },
    { label: 'Dogue de Bordeaux' },
    { label: 'Drentsche Patrijshond' },
    { label: 'Drever' },
    { label: 'Dutch Shepherd' },
    { label: 'English Cocker Spaniel' },
    { label: 'English Foxhound' },
    { label: 'English Setter' },
    { label: 'English Springer Spaniel' },
    { label: 'English Toy Spaniel' },
    { label: 'Entlebucher Mountain Dog' },
    { label: 'Estrela Mountain Dog' },
    { label: 'Eurasier' },
    { label: 'Field Spaniel' },
    { label: 'Finnish Lapphund' },
    { label: 'Finnish Spitz' },
    { label: 'Flat-Coated Retriever' },
    { label: 'French Bulldog' },
    { label: 'French Spaniel' },
    { label: 'German Longhaired Pointer' },
    { label: 'German Pinscher' },
    { label: 'German Shepherd Dog' },
    { label: 'German Shorthaired Pointer' },
    { label: 'German Spitz' },
    { label: 'German Wirehaired Pointer' },
    { label: 'Giant Schnauzer' },
    { label: 'Glen of Imaal Terrier' },
    { label: 'Golden Retriever' },
    { label: 'Gordon Setter' },
    { label: 'Grand Basset Griffon Venden' },
    { label: 'Great Dane' },
    { label: 'Great Pyrenees' },
    { label: 'Greater Swiss Mountain Dog' },
    { label: 'Greyhound' },
    { label: 'Hamiltonstovare' },
    { label: 'Hanoverian Scenthound' },
    { label: 'Harrier' },
    { label: 'Havanese' },
    { label: 'Hokkaido' },
    { label: 'Hovawart' },
    { label: 'Ibizan Hound' },
    { label: 'Icelandic Sheepdog' },
    { label: 'Irish Red and White Setter' },
    { label: 'Irish Setter' },
    { label: 'Irish Terrier' },
    { label: 'Irish Water Spaniel' },
    { label: 'Irish Wolfhound' },
    { label: 'Italian Greyhound' },
    { label: 'Jagdterrier' },
    { label: 'Japanese Chin' },
    { label: 'Japanese Spitz' },
    { label: 'Jindo' },
    { label: 'Kai Ken' },
    { label: 'Karelian Bear Dog' },
    { label: 'Keeshond' },
    { label: 'Kerry Blue Terrier' },
    { label: 'Kishu Ken' },
    { label: 'Komondor' },
    { label: 'Kromfohrlander' },
    { label: 'Kuvasz' },
    { label: 'Labrador Retriever' },
    { label: 'Lagotto Romagnolo' },
    { label: 'Lakeland Terrier' },
    { label: 'Lancashire Heeler' },
    { label: 'Lapponian Herder' },
    { label: 'Leonberger' },
    { label: 'Lhasa Apso' },
    { label: 'Lwchen' },
    { label: 'Maltese' },
    { label: 'Manchester Terrier Standard' },
    { label: 'Manchester Terrier Toy' },
    { label: 'Mastiff' },
    { label: 'Miniature American Shepherd' },
    { label: 'Miniature Bull Terrier' },
    { label: 'Miniature Pinscher' },
    { label: 'Miniature Schnauzer' },
    { label: 'Mountain Cur' },
    { label: 'Mudi' },
    { label: 'Neapolitan Mastiff' },
    { label: 'Nederlandse Kooikerhondje' },
    { label: 'Newfoundland' },
    { label: 'Norfolk Terrier' },
    { label: 'Norrbottenspets' },
    { label: 'Norwegian Buhund' },
    { label: 'Norwegian Elkhound' },
    { label: 'Norwegian Lundehund' },
    { label: 'Norwich Terrier' },
    { label: 'Nova Scotia Duck Tolling Retriever' },
    { label: 'Old English Sheepdog' },
    { label: 'Otterhound' },
    { label: 'Papillon' },
    { label: 'Parson Russell Terrier' },
    { label: 'Pekingese' },
    { label: 'Pembroke Welsh Corgi' },
    { label: 'Perro de Presa Canario' },
    { label: 'Peruvian Inca Orchid' },
    { label: 'Petit Basset Griffon Venden' },
    { label: 'Pharaoh Hound' },
    { label: 'Plott Hound' },
    { label: 'Pointer' },
    { label: 'Polish Lowland Sheepdog' },
    { label: 'Pomeranian' },
    { label: 'Poodle Miniature' },
    { label: 'Poodle Standard' },
    { label: 'Poodle Toy' },
    { label: 'Porcelaine' },
    { label: 'Portuguese Podengo' },
    { label: 'Portuguese Podengo Pequeno' },
    { label: 'Portuguese Pointer' },
    { label: 'Portuguese Sheepdog' },
    { label: 'Portuguese Water Dog' },
    { label: 'Pudelpointer' },
    { label: 'Pug' },
    { label: 'Puli' },
    { label: 'Pumi' },
    { label: 'Pyrenean Mastiff' },
    { label: 'Pyrenean Shepherd' },
    { label: 'Rafeiro do Alentejo' },
    { label: 'Rat Terrier' },
    { label: 'Redbone Coonhound' },
    { label: 'Rhodesian Ridgeback' },
    { label: 'Romanian Mioritic Shepherd Dog' },
    { label: 'Rottweiler' },
    { label: 'Russell Terrier' },
    { label: 'Russian Toy' },
    { label: 'Russian Tsvetnaya Bolonka' },
    { label: 'Saint Bernard' },
    { label: 'Saluki' },
    { label: 'Samoyed' },
    { label: 'Schapendoes' },
    { label: 'Schipperke' },
    { label: 'Scottish Deerhound' },
    { label: 'Scottish Terrier' },
    { label: 'Sealyham Terrier' },
    { label: 'Segugio Italiano' },
    { label: 'Shetland Sheepdog' },
    { label: 'Shiba Inu' },
    { label: 'Shih Tzu' },
    { label: 'Shikoku' },
    { label: 'Siberian Husky' },
    { label: 'Silky Terrier' },
    { label: 'Skye Terrier' },
    { label: 'Sloughi' },
    { label: 'Slovakian Wirehaired Pointer' },
    { label: 'Slovensky Cuvac' },
    { label: 'Slovensky Kopov' },
    { label: 'Small Munsterlander Pointer' },
    { label: 'Smooth Fox Terrier' },
    { label: 'Soft Coated Wheaten Terrier' },
    { label: 'Spanish Mastiff' },
    { label: 'Spanish Water Dog' },
    { label: 'Spinone Italiano' },
    { label: 'Stabyhoun' },
    { label: 'Staffordshire Bull Terrier' },
    { label: 'Standard Schnauzer' },
    { label: 'Sussex Spaniel' },
    { label: 'Swedish Lapphund' },
    { label: 'Swedish Vallhund' },
    { label: 'Taiwan Dog' },
    { label: 'Teddy Roosevelt Terrier' },
    { label: 'Thai Ridgeback' },
    { label: 'Tibetan Mastiff' },
    { label: 'Tibetan Spaniel' },
    { label: 'Tibetan Terrier' },
    { label: 'Tornjak' },
    { label: 'Tosa' },
    { label: 'Toy Fox Terrier' },
    { label: 'Transylvanian Hound' },
    { label: 'Treeing Tennessee Brindle' },
    { label: 'Treeing Walker Coonhound' },
    { label: 'Vizsla' },
    { label: 'Weimaraner' },
    { label: 'Welsh Springer Spaniel' },
    { label: 'Welsh Terrier' },
    { label: 'West Highland White Terrier' },
    { label: 'Wetterhoun' },
    { label: 'Whippet' },
    { label: 'Wire Fox Terrier' },
    { label: 'Wirehaired Pointing Griffon' },
    { label: 'Wirehaired Vizsla' },
    { label: 'Working Kelpie' },
    { label: 'Xoloitzcuintli' },
    { label: 'Yakutian Laika' },
    { label: 'Yorkshire Terrier' }
]    